### ISSUE TITLE
parse error of css

### ISSUE THREAD

**Issue by flip111** [gillchristian/tailwind-purs#14]
```css
@-webkit-keyframes button-pop {
  0% {
    transform: scale( var(--btn-focus-scale, .95) );
  }

  40% {
    transform: scale(1.02);
  }

  to {
    transform: scale(1);
  }
}
```

```
"output.css" (line 2164, column 1):
unexpected '}'
expecting "/*", "@media", "@", ".", white space or end of input
```

parse error occurred on last line of snippet
